### ISSUE TITLE
Add Pokemon lookup function

### ISSUE THREAD

**Issue by theastrogoth** [theastrogoth/tera-raid-builder#107]
A way to search for a Pokemon with access to an ability and/or moves (similar to the Discord bot's search function) would be helpful.

For this, it would probably be a good idea to download all of the pokemon data we're using along with the app bundle, rather than fetching it as needed.

**Comment by Ericzklm** [comment]
I think implementing something like Showdown's teambuilder search system would be good. The only gripe I have with it is that you can only do "and"s and not "or"s
