### ISSUE TITLE
Special Moves

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#11]
Some Pokemon have special moves obtained through distributions or trick room Indeedee-F

**Comment by theastrogoth** [comment]
Do you have a list of these handy? I was only aware of TR Indeedee-F.

**Comment by Ericzklm** [comment]
Honestly, I thought there were more in this category than there actually are but heres some I could find: Pikachu, Raichu, Flabebe, Floette, Florges, H-Zorua, H-Zoroark, Indeedee-F, Tatsugiri-Stretchy. Only Indeedee-F with Trick Room is really relevant, the rest are Fly Pikachu or collectable moves like celebrate or happy hour.

**Comment by Ericzklm** [comment]
Added Trick Room as TM Move to Indeedee-F
