### ISSUE TITLE
Hisuian Samurott missing egg moves

### ISSUE THREAD

**Issue by Osherio** [theastrogoth/tera-raid-builder#111]
Looks like Hisuian Samurott is missing it's egg moves. Tried to put Night Slash and it isn't showing up along with all the other egg moves. I'm not sure if that extends to other Hisuian forms.

**Comment by theastrogoth** [comment]
Thanks for the heads up! It looks like other Hisuian forms are missing egg moves, too.

**Comment by theastrogoth** [comment]
This should be fixed now. Thanks!
