### ISSUE TITLE
Support Finite Field Modifiers

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#126]
What would be the best approach to shutting off cheers, screens, tailwind, weather, etc? The issue is that these modifiers might not have a set number of turns (I believe its confirmed that cheers have some randomness in how long they last). So doing this automatically might not be ideal but there should be someway to deactivate the effects.

**Comment by theastrogoth** [comment]
I'm not sure what the best way to do this would be. Maybe we could have a "Field Effect Duration" input in the move options menu? We would have to display in the calc results when it ends, and you could adjust the duration to get it to end when you want (which would require clicking back and forth and would be tedious). 

Deactivating manually seems like it would be difficult if we want to consider each type of effect (screens, weather, terrain, cheers, TR, tailwind) separately. We could have an option to clear all field effects at the start of a turn without needing to add a bunch of toggles, but that seems less useful. 

I'm inclined to handle it automatically, and assume the shortest possible duration for each thing. I'm not really sure if durations are for the entire team or per-raider, though. 

> I believe its confirmed that cheers have some randomness in how long they last

Interesting. [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Tera_Raid_Battle#Cheers) seems to indicate that cheers last 3 turns, regardless or fainting or being nullified. Testing the durations of things ourselves seems like it would be a huge pain. It sounds like someone has already done this, though?

**Comment by Ericzklm** [comment]
IIRC these items are based on moves uses instead of turns since the idea of turns doesn't really exist. So if only one person is actually moving a cheer can last for quite a while. I think this info was from Anubis
