### ISSUE TITLE
Graphic Bug Fixes

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#128]
http://theastrogoth.github.io/tera-raid-builder/#H4sIAAAAAAAAA8VY227bOBD9FUIP2xarppZ8S/KWS7cJUBdB7N2X1FgwEm2xpkiDouy6Rf99z1CSrRTFboJuFTihRkNyZs7cKOlrsAhOg+RTYXQQBi44vbvrhYHmuQjmIZEyJSIKg7IQ9vqSFnG7FM6TZu2k0QWtiMNgaU25Bjc3G3GtFwbkvSmKSXNbCUysdJgpRGJ0yu3u7WIhEleAZY1SuGTSeYnDMOCJkxvuxExYXm/PSAN3K4ypWJCgNfdj6kexXzazcrkUlgyWuTjcFZkUKr3gOhHqkud8KfbM6vYWCn/A8jb8mH2Rcb0UtZ+0cYLQJFak0uNam5XIK/+WVhPHe8pDFmvBXeNAOIA0e+97TXpHYO+lko4o6UTu5yGHVogNyZB+VGIjyHsO9sx2a1HHoWiCUCon10p6F4jPzvJJPdsAcvDwPAw2wenXAGlwEgYTsXVbwy6tWRfMGfb+gs0qAbNMFIJxKxjQslxw7WjBvWCFE+vX97vXdGVSF86Wic+RkLlMMDKJGZsKy2TBPpWF3yeVAmXhTZaZrV9YCFeu2dbYVXH0UX/U52JhoK4oFwuZSKGd2rFU3ONWpCHbmfKFUmxb2+G1SF0rMguWk6KitBtkU+VNWqYEL9wpMOkVdxhC9s4KvuEWEq9gjNbcW63ZBU+04LUhbivAIiN5kpSWJ7CEXBSyNbdc7QoJkuuUFTRshFQhq125BVKWcVjHcbEpo9RkCuukXjJK/CN2pneeggbuWGoY6kSjQqrN5GK51HACf+AD7IMprFhnAm7yS7na8l1Bsth96Zh0LwofLmBU2MnZvVyyhKOuGXxLahJh9RFDcMHeIC+ZF4ZAcUZVy0zjCegRiSQjSBJMYbaUlU+qOC53TOY5CgC02oXeAJdBEv4o+0QONiu1kisittJlh7B7P9eKuPN87ycEkjvHkxU5q8hMqdLKmb+P2JmfCImckm1cHVjRnnUpFkIXArw+8UTKtplMMraUqAV2Y7ZIF3SKNQA747ABKvuD3vnNEZK+fPNO5nK1K/9mvzH75gZVfWMsrXq7QUKyWy5TNi3XazDZTHCU6p0vpagXoiP56XOUYtBUVhAuuII1wZ8IsN1QyV6gsJCZ58JaKviJSXEfhF7MOCQ58TAOR37szb81E/3ouz9MRT0ovSl2CRDCEiIRG/gbcq8TAR1kYeDTZurThvRzlbOJ1NT0hz1IuGuxgIGsmVdaj70G+h/SJRz3wj5MaowCB81wZndw1hVyZ1KJp6AGIboCYE+pPv5CfWDm7UYa1CUtOkvRXPUBdVTBJU2QOeg9CvgltytCfa2XlkvqvTNc1b3iX0jHO2u2LgNxiDlw0c67Pbze4fcAVuz7HwBpnpCsff9ocE0MEvMcZbbyzbIF7Rwze1w+hmF0TBrGo8eg0qVSwHRrkhWb5rwgANOVdOj5dJ/QofheLjPHpjh9BKG+EmpN5XLFfUwfh7BPDqo6YdAmK3h/KHSc3X8Cq8bBE3BNyvT1VHE64Ck1UAiWMnSquaUUubClTrKngKibeNCiKghXaIGPiU1vQOPjaq0BgSqjvsj+kL6i3suFQN/ZgvxQfvniD/gza3JkTIKy8vX0r4DmdRcZeJYnAe3lB8PoBH8VoMxq9rDuJ3VXySnto4NP+u3yJlwPd1WeyflnbKoU1/sGWBntRdQtlKFTkQefoPzlxOAU9k9OyMhXTzMhbpnwXcrHHZnQb5tQ5WS/I9WDlurvEmzQkQlD+LkR9LDHdOX/UcuCVn/oKgbjlvqHBXwIzy824bhlwv5g66oCT+Dpn+s+t8I/mH8QS/gOxP7N70m9iM6UZ+4EUdS2odtWEMUt3c/UC6J+y4ZnOhAiakmNJDrPGwM6S4Jhy4Cuk2DU0v1cSTBGR96XduuRtLMAHLcM6DoAJy3dzXNdV56Pey3l7deazh7GIpyGjwp9LeT/1h/jKNyn//6toavgx30chs9cfbE/CZ81CYZ0DjaimhfqzrSP6CQ89P/WW+7hXeFX2zBu21B9bmpOoc5y8ZhO40ZU62vGIRKjH1ngZf68GXg5vev5794xIA/8V/sRmsMxqBPi9yhJ4KWoT3f+1IxGRI6pf6ONxrQ9jmiIaaB1MQmKhzTgoX9M1+O519L+jfyPvobhbj7/9u0fdas5AswYAAA=

raidInputProps has the 4th raider's id set at 3 instead of 4. Causes issues with the moveTypes and learnMethods. Stat clears should follow a format like "Mewtwo uses Clear Debuffs on Mewtwo" or "Mewtwo uses Clear Boosts on Raiders"

**Comment by theastrogoth** [comment]
These should be fixed!

The id problem was a copy/paste oversight when setting the default raiders to Mew. I've changed the strat/hash loader to ensure that the ids of raiders match their position in the array, so there's no need to recreate your link.
