### ISSUE TITLE
Support For Skill Swap, Entrainment, Worry Seed, Receiver, etc

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#14]
Add the ability to access abilities that are not normally possible. Example: Skill Swap Pure Power. An option would be to check if any Pokemon has one of those moves and add their abilities to all drop downs if so. An extra step would be ensuring that abilities like Protosynthesis cannot be overwritten.

**Comment by theastrogoth** [comment]
These are already supported as part of the raid simulation (i.e. you can use Skill Swap as a move and it will result in the appropriate ability changes in subsequent moves). Do you think this is too restrictive? It forces you to make sure your setup can actually make the ability change happen.

Good call about un-overwritable moves. I still need to add checks for those, I think.

**Comment by Ericzklm** [comment]
Im just now noticing that it's already implemented in the calculations. I like the approach you took here by keeping the builds "valid" while taking them into consideration in the calculations, so it's fine.
