### ISSUE TITLE
Unable to Delete Substitute

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#145]
Is there a way to delete a substitute after creating it? 
<img width="270" alt="image" src="https://github.com/theastrogoth/tera-raid-builder/assets/52121058/f9a95a6b-11a1-47f5-aad1-7dcae39dfe4e">
An 'X' in the popup would make the most sense

**Comment by theastrogoth** [comment]
Good idea! It also looks like the buttons may need to be widened slightly...
