### ISSUE TITLE
Clearer IV text in graphics for edge cases

### ISSUE THREAD

**Issue by theastrogoth** [theastrogoth/tera-raid-builder#148]
[Raised by H](https://discord.com/channels/837300721463328788/1045412612688592916/1176019082655567934).

Currently, any IVs that are maxed are not shown. There's not an easy way to specify when only particular stats need to be maxed, and "All Hypertrained" is often not strictly necessary. 

I can't think of an intuitive way to let the user select which IVs don't matter.

**Comment by Ericzklm** [comment]
One approach is to have "Best: HP, Def" with "All Hypertrained" or "Any" representing the edge cases. Maybe some logic that instead lists "0 IVs: Atk, Speed" if there are only one or two that are 0.

Another Approach is to list the numbers as "\*/0/31/31/\*/\*"

Another approach is to do something like this:
<img width="121" alt="image" src="https://github.com/theastrogoth/tera-raid-builder/assets/52121058/943dd255-783f-4d9f-97f4-fc0d925a7b88">

I'm not sure how much sense the numbers make to someone whose not as familiar with the mechanics.
