### ISSUE TITLE
Move Boxes Size

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#16]
Adjust the move boxes to be slightly shorter, currently the container for the moves holds just about exactly 3 moves before you have to scroll. Making them slightly shorter allows you to see part of the 4th move box to indicate there are more boxes below.

**Comment by theastrogoth** [comment]
The boxes have been shrunk, and now their container holds a little more than 4, hopefully making it easy to see that you should scroll to the added moves below
