### ISSUE TITLE
Arceus Implementation

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#193]
Automatically switch Arceus forms depending on the held plate. Possibly also remove all non-base Arceus forms.

**Comment by theastrogoth** [comment]
I think this would be nice. All of the Arceus forms take up a lost of space in the dropdown and search lists. 

Would you want to use the same kind of approach for other item-related form changes? Zacian, Zamazenta, Ogerpon, etc
