### ISSUE TITLE
Feedback on a few things that could be changed

### ISSUE THREAD

**Issue by smxz322000** [theastrogoth/tera-raid-builder#197]
1. 'LOAD BOSS SET' cannot be searched in translated languages (e.g. Chinese).
2. 'Cheers' (e.g. Go all out, Hang tough, Heal up). 
3. 'Weather' (e.g. Sunny Day, Orichalcum Pulse). 
The tool itself is really cool, thanks!

**Comment by theastrogoth** [comment]
Thanks for the feedback! I will fix issue 1 ASAP.

Regarding 2 and 3, I'm not sure exactly what kind of changes are you suggesting:

   2. Rename cheers to the proper in-game name (e.g. "Attack Cheer" becomes "Go all out")?
   3. A readout in the Move Order menu to display weather (and maybe terrain)?
