### ISSUE TITLE
Missing elements/mechanics from Tera Raids

### ISSUE THREAD

**Issue by GritzStelly** [theastrogoth/tera-raid-builder#198]
Original Title: No way to enable tera on players
I don't see an option to terrastalize on a given turn. i might just be missing it

**Comment by GritzStelly** [comment]
And it's not clear if mechanics like player/boss stat reset and tera orb charge or other RNG-based mechanics are implemented

**Comment by GritzStelly** [comment]
Also double attack turns from the boss

**Comment by theastrogoth** [comment]
Thanks for raising the issue! I believe all of these things are implemented, but they're not that obvious, so maybe we need to rethink the UI a bit.

To enable Tera, you can find the option to do so by clicking the "hamburger" menu button in a move selection box: 
<img width="450" alt="tera_switch" src="https://github.com/theastrogoth/tera-raid-builder/assets/52220914/32359989-fa8b-4e7d-9645-a830b1167302">

While the Tera Charge is not displayed anywhere, flipping the Tera switch does nothing if the raider doesn't have enough charge. Here is an example strategy with terastalization: https://theastrogoth.github.io/tera-raid-builder/#blastoise/edgelord

Boss actions like stat resets are also already implemented: 
<img width="452" alt="boss_moves" src="https://github.com/theastrogoth/tera-raid-builder/assets/52220914/78e7d22a-c3ed-4a92-ac43-7aa7501c805e">

For scripted boss moves (double attack turns), you can leave a raider's move as "(No Move)" but select a move for the boss. This also lets spread moves from the boss hit all raiders, like Venusaur's Petal Blizzard from the previous event.

I'm not sure what kinds of RNG-based mechanics you're thinking of, but in general, things that depend on RNG like flinching, stat boosts/drops that aren't guaranteed, or sleep wearing off are handled by the "Effect" and "Roll" switches in the first screenshot. These are also controlled by the Best/Average/Worst case buttons. 


Let me know if you have any particular ideas about how to make these things more intuitive!
