### ISSUE TITLE
Add Substitute Builds

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#2]
For each of the raider slots, it would be nice to have a dropdown menu or something that you can use to select between alternate builds that can fit that slot. The moves and the calc's would need to be adjusted accordingly.

**Comment by theastrogoth** [comment]
That's a great idea! I'll need to do some thinking about the best way to keep track of moves that fill the same role (e.g. Fake Tears, Acid Spray, Lumina Crash) for the purposes of substituting a new build into a calc
