### ISSUE TITLE
Timing of End-of-Turn Effects

### ISSUE THREAD

**Issue by theastrogoth** [theastrogoth/tera-raid-builder#220]
It has been reported that things like Grassy Terrain healing and Burn Damage should occur every 4 moves (for all raiders simultaneously) rather than once per move. I'm not sure whether or not this timing applies to the boss as well.

**Comment by Ericzklm** [comment]
The burn damage occuring every 4 moves is correct, I have a clip somewhere showcasing this that I can try to dig up if more information is needed. This does also apply to the boss which is what stops something like Toxic from doing exponential damage on the boss.

I seem to remember Grassy Terrain behaving normally on a move-by-move basis but I am not confident in that claim.
