### ISSUE TITLE
Allow selecting Struggle as a move

### ISSUE THREAD

**Issue by SadisticMystic** [theastrogoth/tera-raid-builder#229]
I have a use case where I sometimes bring a Choice Band Technician Toxtricity to raids, with Belch as its only move. The interface here doesn't have any problem with allowing the use of Belch despite not eating a berry yet, but the entire point of this set is to attack immediately with Struggle, which only takes one click rather than the usual three. It's mainly useful for KOing low-star raids quickly (or Ditto raids where the host properly brings a weakling), but Struggle is not selectable from the drop-down menus here, so I can't use it to test which 3-star raids are frail enough to be OHKO'd.

Perhaps it makes sense to allow Struggle to be freely input into the move order at any time, or maybe only if Belch, Stuff Cheeks, or Assault Vest are present in the set.

**Comment by theastrogoth** [comment]
Thanks for the suggestion! This is a neat use case. I wouldn't have thought to save time by skipping move choice via Struggle.

I've modified the move selection field to allow Struggle to be selected when there aren't any other useable moves. The easiest way to make it available to a raider would be to leave their moveset blank, but it will also pop up in some of the appropriate situations (Belch before eating a berry, Gigaton Hammer after using it last turn, Assault Vest and only Status moves, etc).

Let me know if anything seems inaccurate/off with the new Struggle option and I'll reopen this issue :)
