### ISSUE TITLE
Inconsistent Attack Cheer Duration

### ISSUE THREAD

**Issue by SelBast** [theastrogoth/tera-raid-builder#230]
I have noticed with [this setup](https://theastrogoth.github.io/tera-raid-builder/#KITu5BCf), that the duration of the attack cheer is inconsistent between activated and deactivated Optimize Boss Moves.
Without it active the Ice Burn from Kyurem receives the boost from it's own previous attack cheer, while with the boost ends after the charging turn.

**Comment by theastrogoth** [comment]
Thanks for the bug report! 

There were some problems with the way turn numbers were being tracked with the automatic moves by NPCs, but I believe they're handled correctly now. 

If you reload the link you've shared, Attack Cheer duration will no longer be affected by optimizing the boss's moves.
