### ISSUE TITLE
Instruct should always fail when used against the raid boss

### ISSUE THREAD

**Issue by SadisticMystic** [theastrogoth/tera-raid-builder#231]
https://theastrogoth.github.io/tera-raid-builder/#JqnhxiTX
This is a plan that works according to the site, but doesn't work when you put it into practice. It turns out Instruct will fail not only after scripted moves, but in *any* case where you use it against the raid boss. For that matter, it also won't cause the boss's response in your lane to be an attack against *itself*, like it's shown doing here.

**Comment by Ericzklm** [comment]
Good catch! When Instruct is targeted into the boss, there should no longer be any effect.

Thanks for the report!
