### ISSUE TITLE
Support Strategy Titles

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#34]
Add support to give a title to a strategy that can be listed above the builds (and maybe a subtitle as well?). This would need to be stored and incorporated into the hash.

**Comment by theastrogoth** [comment]
How do you imagine the subtitles working? Two separate text input fields, or something else?

**Comment by Ericzklm** [comment]
Yep, two separate input fields but the subtitle is not really necessary at all to be honest. If it were to be implemented, it could be defaulted with a generic description depending on the raid boss: "A Tera Raid Strategy for 6-Star Dondozo"
