### ISSUE TITLE
Unable to Change

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#36]
There seems to be a bug that does not allow me to change the Pokemon. The builds keep going back to the default when I click on another Pokemon and the abilities that are available are the abilities of the default option originally in that slot.

**Comment by Ericzklm** [comment]
```
self.onmessage = (event: MessageEvent<{info: RaidBattleInfo}>) => {
    const raidersMessage = event.data.info.startingState.raiders;
```
This fires every time you make a change and reloads the starting state rather than just firing once at the beginning. From the worker code in a92dfc8.

**Comment by theastrogoth** [comment]
I think the cause of this was my misuse of `React.memo()`. I'm still not entirely sure why it wasn't working before, but the issue seems to be fixexd.
