### ISSUE TITLE
Support Legacy Hashes

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#37]
A possible solution to hashes breaking in the future is to associate a version number to each hash. Each hash is uncompressed according to the correct version and any fields not present will be filled with something generic. This is not the cleanest solution since it requires tracking and maintenance of legacy versions of the data structures and hashes.

**Comment by theastrogoth** [comment]
My hope is that any future changes will only involve adding keys/data to the object read from the hash. Then, we would just have to make sure that we supply a default value if any of the new keys are missing. I don't think this would require reading a version number, just a check whether a key holds any value or is `undefined`.

If we end up reorganizing the information stored in the hash, the version number is a good solution.
