### ISSUE TITLE
Additional Fields

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#48]
Possible additional user input fields to add (may break hashes):

- A strategy description
- A place to put notes
- Credits

**Comment by theastrogoth** [comment]
Does a single text area to store this sound okay, or do you think it would benefit from having 2 or 3 separate spots for different things? 

FYI, I don't think we need to worry too much about hash backwards compatibility when adding things. It's relatively easy to deal with hashes that are missing info. For example, the test link I used [here](https://github.com/theastrogoth/tera-raid-builder/pull/29#issuecomment-1640669673) still works even though strategy titles and move groupings weren't implemented at the time it was generated.

**Comment by Ericzklm** [comment]
> FYI, I don't think we need to worry too much about hash backwards compatibility when adding things. It's relatively easy to deal with hashes that are missing info. For example, the test link I used https://github.com/theastrogoth/tera-raid-builder/pull/29#issuecomment-1640669673 still works even though strategy titles and move groupings weren't implemented at the time it was generated.

Thats good to know!

I think having different spots would make sense, the description goes somewhere near the title and the notes and credits can go somewhere towards the bottom of the page. The notes and credits can probably be in the same spot but be separate input fields.
