### ISSUE TITLE
Move Adding and Deleting

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#5]
Add a minus button on each move row and a plus button after move rows to add and delete from anywhere instead of only adding and deleting from the top (bottom?) of the stack. Bonus point if you can drag turns around.

**Comment by theastrogoth** [comment]
@Ericzklm  Any thoughts on the draggable moves? I still need to add the plus/minus buttons for inserting and removing directly from different spots, but things are easier to move around now

**Comment by Ericzklm** [comment]
Yep! What you've implemented is exactly what I was thinking of. When the grouping functionality is added, it would be nice if you could drag a box on top of a group to add it to the group, or drag it out of the group to remove it.

**Comment by theastrogoth** [comment]
There are now some new buttons for inserting and removing rows. Any thoughts about how they look?

**Comment by Ericzklm** [comment]
Sorry in advance, this is very pedantic.

I was thinking about something like this:
<img width="690" alt="image" src="https://github.com/theastrogoth/tera-raid-builder/assets/52121058/d8c0bcd9-5f21-4bd6-8505-b3d19af8fd4b">

- X moved to the right side to balance out whitespace on the edges of the move box and because I associate the 'X' with the right side for some reason
- Moved "Crit, Effect, Roll" closer to the dropdown menus for balance
    - The horizontal line that runs down the middle of a box may need to be adjusted
- Added one buttons to add groups/moves between the boxes that are explicitly labeled as "Add" or "New"
    - With how the drag and drop works, you can treat these "Add" buttons as it's own row allowing you to drag a move between a move item and an add item. When you release the box, the "Add" buttons would correct itself to be between each move box again.

**Comment by theastrogoth** [comment]
I like your proposed layout because:
- it is more clear/intuitive
- it would likely be easier for mobile users with clumsy thumbs (like me)

My main concern is that we would sacrifice a bit of vertical space for this.

Note that I wasn't feeling confident that I could pull off the nested Drag/Drop behavior that your vision for move groups would probably involve, so I've come up with something a little different (see #38) that doesn't require any "Add Group" button.  I'm open to changing this if you have any hints about making a click-and-drag-window approach happen.

**Comment by theastrogoth** [comment]
@Ericzklm I've modified the buttons to look a bit more like the setup you've proposed. Thanks for the suggestions! I think it's made thing a bit easier to use, especially on mobile. Any more notes?

**Comment by Ericzklm** [comment]
Add move looks great! 

I think the combining groups part isn't the most intuitive and beautiful-dnd makes it a little difficult to successfully do combines without re-ordering them instead. I think the best approach is still the nested groups and turns that would entirely rely on drag-and-drop with an explicit add-groups button but maybe this is something to file away for another day.

```
<DragDropContext>
    <Droppable>
        <Draggable> (group)
            <Droppable>
                <div> (add turn)
                <Draggable> (turn)
                <div> (add turn)
                <Draggable> (turn)
                <div> (add turn)
            </Droppable>
        </Dropabble>
        <div> (add group (& turn))
        <Draggable> (group)
             <Droppable>
                 <div> (add turn)
                 <Draggable> (turn)
                 <div> (add turn)
             </Droppable>
        </Draggable>
    ...
```
...So basically a Kanban board. But yea, I can see your concern with too much vertical space used up by add turns/groups in this case.
