### ISSUE TITLE
Minor Asset Issues

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#51]
...More issues with the assets

The starter evolution lines' Sugimori arts have an extra white trim: needs to be manually removed
Mimikyu sprite linking is broken: probably need to rename the sprite

**Comment by theastrogoth** [comment]
Sorry about all of the name issues. For Pokemon with multiple forms, I'd been using a strange mix of the Smogon and PokeAPI naming conventions.
