### ISSUE TITLE
Sandstorm Chip

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#70]
Add the damage from sandstorm
Ground, steel, and rock are immune (can tera into or out of the immunity)
Safety Goggles
Sand Rush

Chip damage happens very early in end-of-turn resolution (2nd check)

**Comment by theastrogoth** [comment]
I think Sandstorm damage is already handled, as well type immunities and Safety Goggles, by `smogon/calc`:

https://theastrogoth.github.io/tera-raid-builder/#H4sIAAAAAAAAA72TS2+cMBDHvwqaXlLJhwU2D+0tj6rNYasqyQ1xcGDYuBib2mYVEu1379iYbNoot2wEGg3z+v9gzDM0sILqt9UKGDhYFcWCgeIdQsm8K+roVEY4KrFYaVVzM35rGqycpZDRUvqilMFg0Vxf+UncbNAFV/dOaGV9RcZgY/TQU7TTW7xWjSb3Xlu7nh+nOUo79KMrg7UIIr1usZsgB6N8JEyyke7Bz+SuJVtj4zl7HmwdLEZ1QkWI70f190IKN5InHHYhTsN9BrdeQQQrcYvS66Lhd2OPEd7O5IN0opcCje97dIavQ7YsGWxh9Qz0TU8YQLyLEDhjxHzDRZ1c0Ajw/vhn4E+e+einTs4nsq/A1CAlgx/c1MQZek+p9+Uqd3MwT/+7KZUuFtOAogx+Uc71ZyydANAkX1JSvRsNV4LWRv4tV3Vy6wzy7oAA2R4g8wBCtdyFDX/SF8j3ADmp/uKSdkGv/nkEyz3BklTXohPtOLzRp4U06Mbku95sZDh4H8hSxiN5zGIuPBHZuXO8apPLB/RHO6V0yOSs4dJitNAJBTRk99Lm0f0fQNwL6oo9zgw4Gej4Y+iYe46p6h/hVxOyA6pm76rmB1TN31VdHkC1DCve/QWMxEqL5gUAAA==

Related: I think end-of-turn damage/healing for Raid Bosses needs to get divided by their HP multiplier. It should use percent of base HP for bosses, right?

**Comment by Ericzklm** [comment]
I'm guessing I had Grassy Surge Rillaboom as the raid boss when I checked; it looks like its working fine.

>Related: I think end-of-turn damage/healing for Raid Bosses needs to get divided by their HP multiplier. It should use percent of base HP for bosses, right?

I believe so? This should also apply for things like Belly Drum
