### ISSUE TITLE
Preset Builds

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#75]
Create and add preset builds for raiders somewhere in the build controls or the import/export menu using a dropdown menu.

**Comment by theastrogoth** [comment]
Do you think we should use the presets from showdown usage data like the showdown calculator, or build our own list of raid DPS/support presets?

**Comment by Ericzklm** [comment]
I dont think the showdown sets are of any use, we'll have to build our own. Examples: "Standard Gholdengo", "AP Moist Bull", etc.
