### ISSUE TITLE
Automatic testing?

### ISSUE THREAD

**Issue by theastrogoth** [theastrogoth/tera-raid-builder#86]
At least a couple of times, something has broken without my noticing when implementing a new feature. Most recently, I broke instruct when getting an implementation for choice locking started.

I don't have any experience with tests in Javascript/React, but having several test cases for all of the RaidCalc stuff would help prevent similar issues in the future

**Comment by Ericzklm** [comment]
Agreed, this is probably important. My manager would have wanted me to have a unit test suite 😆
