### ISSUE TITLE
Graphic generation/download broken on iOS Safari

### ISSUE THREAD

**Issue by theastrogoth** [theastrogoth/tera-raid-builder#98]
I'm not sure yet exactly where the issue lies, but it seems like a browser-specific problem with something happening during generation:

- If "Download" is pressed with a strategy with a single move (after filtering out "(No Move)" ones), I'll get a prompt to download "failed_generation.png".

- If "Download" is pressed with a strategy with 2 or more moves, nothing happens. 

I'm not sure if it is primarily a Safari issue or a mobile issue. Tested with iOS 16.3.1

**Comment by theastrogoth** [comment]
Behavior on Chrome for iOS seems to be the same, so maybe it is an OS problem. It looks like FileSaver.js and iOS can sometimes have issues, but I'm not convinced that's the problem.

**Comment by Ericzklm** [comment]
I didn't have any issues with Safari so its probably just and IOS issue

**Comment by Ericzklm** [comment]
Doesn't work on Android either

**Comment by theastrogoth** [comment]
Are you getting a prompt to download the image for failed generation, or does nothing happen?

**Comment by Ericzklm** [comment]
I get the failed generation prompt

**Comment by theastrogoth** [comment]
The above PR is currently live. Mind giving it a quick test?
